### ISSUE TITLE
משתנה גלובלי לא יעבוד כשיש כמה פונקציות שונות

### ISSUE THREAD

**Issue by erelsgl** [samuelharroch/research-algorithms#1]
https://github.com/samuelharroch/research-algorithms/blob/566d09f38b49353eea97cb95ef3665e7f5c10b75/HW2/q2.py#L2

**Comment by samuelharroch** [comment]
דווקא הרצתי שם עם 2  פונקציות שונות וזה עבד.
השתמשתי בDICT ששומר את  שם הפונקציה כמפתח ואת הקלט האחרון כערך ...

**Comment by samuelharroch** [comment]
![image](https://user-images.githubusercontent.com/60176709/157463680-ab0fe9fa-7049-482e-9390-58ddf5628669.png)
לדוגמא עם F וF1

**Comment by erelsgl** [comment]
הבנתי, נכון, עכשיו אני רואה
